In [ ]:
from google.colab import files
uploaded=files.upload()

Saving house_price.csv to house_price.csv


In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


In [ ]:
df=pd.read_csv('house_price.csv')
df

Unnamed: 0      Location  BHK  Furnishing  Sq.ft  Old(years)  Floor  \
0            37  Bommanahalli    3           1   3000           1      3   
1            43  Bommanahalli    3           1   1650          10      0   
2            12    Whitefield    2           0   1000           5      3   
3             8    Whitefield    3           0   1600           1      9   
4             9    Whitefield    2           1   1200           5      1   
..          ...           ...  ...         ...    ...         ...    ...   
995          48  Bommanahalli    3           1   1460           1      2   
996           0    Whitefield    3           0   2100           1      7   
997          42  Bommanahalli    2           0   1033           5      0   
998          39  Bommanahalli    3           0   1500          10      1   
999           3    Whitefield    3           1   1768           5     11   

     Price  
0    28000  
1    18000  
2    16400  
3    27000  
4    20000  
..     ...  
995  25000  
996  28000  
997  16500  
998  22000  
999  30000  

[1000 rows x 8 columns]

In [ ]:
df.shape

(1000, 8)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  1000 non-null   int64 
 1   Location    1000 non-null   object
 2   BHK         1000 non-null   int64 
 3   Furnishing  1000 non-null   int64 
 4   Sq.ft       1000 non-null   int64 
 5   Old(years)  1000 non-null   int64 
 6   Floor       1000 non-null   int64 
 7   Price       1000 non-null   int64 
dtypes: int64(7), object(1)
memory usage: 62.6+ KB


In [ ]:
df.isnull()

Unnamed: 0  Location    BHK  Furnishing  Sq.ft  Old(years)  Floor  Price
0         False     False  False       False  False       False  False  False
1         False     False  False       False  False       False  False  False
2         False     False  False       False  False       False  False  False
3         False     False  False       False  False       False  False  False
4         False     False  False       False  False       False  False  False
..          ...       ...    ...         ...    ...         ...    ...    ...
995       False     False  False       False  False       False  False  False
996       False     False  False       False  False       False  False  False
997       False     False  False       False  False       False  False  False
998       False     False  False       False  False       False  False  False
999       False     False  False       False  False       False  False  False

[1000 rows x 8 columns]

In [ ]:
df.isnull().any()

Unnamed: 0    False
Location      False
BHK           False
Furnishing    False
Sq.ft         False
Old(years)    False
Floor         False
Price         False
dtype: bool

In [ ]:
df.isnull().sum()

Unnamed: 0    0
Location      0
BHK           0
Furnishing    0
Sq.ft         0
Old(years)    0
Floor         0
Price         0
dtype: int64

In [ ]:
x=df.drop('Price',axis=1)
y=df.Price

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [ ]:
x.Location=le.fit_transform(df.Location)
x

Unnamed: 0  Location  BHK  Furnishing  Sq.ft  Old(years)  Floor
0            37         0    3           1   3000           1      3
1            43         0    3           1   1650          10      0
2            12         1    2           0   1000           5      3
3             8         1    3           0   1600           1      9
4             9         1    2           1   1200           5      1
..          ...       ...  ...         ...    ...         ...    ...
995          48         0    3           1   1460           1      2
996           0         1    3           0   2100           1      7
997          42         0    2           0   1033           5      0
998          39         0    3           0   1500          10      1
999           3         1    3           1   1768           5     11

[1000 rows x 7 columns]

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scal=MinMaxScaler()

In [ ]:
x=scal.fit_transform(x)
x

array([[0.75510204, 0.        , 1.        , ..., 0.93509213, 0.        ,
        0.23076923],
       [0.87755102, 0.        , 1.        , ..., 0.36976549, 1.        ,
        0.        ],
       [0.24489796, 1.        , 0.        , ..., 0.09757119, 0.44444444,
        0.23076923],
       ...,
       [0.85714286, 0.        , 0.        , ..., 0.11139028, 0.44444444,
        0.        ],
       [0.79591837, 0.        , 1.        , ..., 0.30695142, 1.        ,
        0.07692308],
       [0.06122449, 1.        , 1.        , ..., 0.41917923, 0.44444444,
        0.84615385]])

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2)

In [ ]:
xtrain.shape

(800, 7)

In [ ]:
xtest.shape

(200, 7)

In [ ]:
ytrain.shape

(800,)

In [ ]:
ytest.shape

(200,)

In [ ]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()

In [ ]:
from sklearn.metrics import r2_score

In [ ]:
model.fit(xtrain,ytrain)

LinearRegression()

In [ ]:
ypred=model.predict(xtest)

In [ ]:
r2_score(ytest,ypred)

0.8318146919332914

In [ ]:
#decision tree
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(xtrain,ytrain)
ypred=model.predict(xtest)
r2_score(ytest,ypred)

1.0

In [ ]:
CLASSIFICATION

In [ ]:
from google.colab import files
uploaded=files.upload()

Saving winequality-red.csv to winequality-red.csv


In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


In [ ]:
df1=pd.read_csv('winequality-red.csv')
df1

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0               7.4             0.700         0.00             1.9      0.076   
1               7.8             0.880         0.00             2.6      0.098   
2               7.8             0.760         0.04             2.3      0.092   
3              11.2             0.280         0.56             1.9      0.075   
4               7.4             0.700         0.00             1.9      0.076   
...             ...               ...          ...             ...        ...   
1594            6.2             0.600         0.08             2.0      0.090   
1595            5.9             0.550         0.10             2.2      0.062   
1596            6.3             0.510         0.13             2.3      0.076   
1597            5.9             0.645         0.12             2.0      0.075   
1598            6.0             0.310         0.47             3.6      0.067   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                    11.0                  34.0  0.99780  3.51       0.56   
1                    25.0                  67.0  0.99680  3.20       0.68   
2                    15.0                  54.0  0.99700  3.26       0.65   
3                    17.0                  60.0  0.99800  3.16       0.58   
4                    11.0                  34.0  0.99780  3.51       0.56   
...                   ...                   ...      ...   ...        ...   
1594                 32.0                  44.0  0.99490  3.45       0.58   
1595                 39.0                  51.0  0.99512  3.52       0.76   
1596                 29.0                  40.0  0.99574  3.42       0.75   
1597                 32.0                  44.0  0.99547  3.57       0.71   
1598                 18.0                  42.0  0.99549  3.39       0.66   

      alcohol  quality  
0         9.4        5  
1         9.8        5  
2         9.8        5  
3         9.8        6  
4         9.4        5  
...       ...      ...  
1594     10.5        5  
1595     11.2        6  
1596     11.0        6  
1597     10.2        5  
1598     11.0        6  

[1599 rows x 12 columns]

In [ ]:
df1.shape

(1599, 12)

In [ ]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB


In [ ]:
df1.isnull()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0             False             False        False           False      False   
1             False             False        False           False      False   
2             False             False        False           False      False   
3             False             False        False           False      False   
4             False             False        False           False      False   
...             ...               ...          ...             ...        ...   
1594          False             False        False           False      False   
1595          False             False        False           False      False   
1596          False             False        False           False      False   
1597          False             False        False           False      False   
1598          False             False        False           False      False   

      free sulfur dioxide  total sulfur dioxide  density     pH  sulphates  \
0                   False                 False    False  False      False   
1                   False                 False    False  False      False   
2                   False                 False    False  False      False   
3                   False                 False    False  False      False   
4                   False                 False    False  False      False   
...                   ...                   ...      ...    ...        ...   
1594                False                 False    False  False      False   
1595                False                 False    False  False      False   
1596                False                 False    False  False      False   
1597                False                 False    False  False      False   
1598                False                 False    False  False      False   

      alcohol  quality  
0       False    False  
1       False    False  
2       False    False  
3       False    False  
4       False    False  
...       ...      ...  
1594    False    False  
1595    False    False  
1596    False    False  
1597    False    False  
1598    False    False  

[1599 rows x 12 columns]

In [ ]:
df1.isnull().any()

fixed acidity           False
volatile acidity        False
citric acid             False
residual sugar          False
chlorides               False
free sulfur dioxide     False
total sulfur dioxide    False
density                 False
pH                      False
sulphates               False
alcohol                 False
quality                 False
dtype: bool

In [ ]:
df1.quality.unique()

array([5, 6, 7, 4, 8, 3])

In [ ]:
x=df1.drop('quality',axis=1)
y=df1.quality

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scal=MinMaxScaler()

In [ ]:
x=scal.fit_transform(x)
x

array([[0.24778761, 0.39726027, 0.        , ..., 0.60629921, 0.13772455,
        0.15384615],
       [0.28318584, 0.52054795, 0.        , ..., 0.36220472, 0.20958084,
        0.21538462],
       [0.28318584, 0.43835616, 0.04      , ..., 0.40944882, 0.19161677,
        0.21538462],
       ...,
       [0.15044248, 0.26712329, 0.13      , ..., 0.53543307, 0.25149701,
        0.4       ],
       [0.11504425, 0.35958904, 0.12      , ..., 0.65354331, 0.22754491,
        0.27692308],
       [0.12389381, 0.13013699, 0.47      , ..., 0.51181102, 0.19760479,
        0.4       ]])

In [ ]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3)

In [ ]:
xtrain.shape

(1119, 11)

In [ ]:
ytrain.shape

(1119,)

In [ ]:
xtest.shape

(480, 11)

In [ ]:
ytest.shape

(480,)

In [ ]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()

In [ ]:
from  sklearn.metrics import accuracy_score

In [ ]:
model.fit(xtrain,ytrain)

LogisticRegression()

In [ ]:
ypred=model.predict(xtest)

In [ ]:
accuracy_score(ytest,ypred)

0.5895833333333333

In [ ]:
#decision tree
from sklearn.tree import DecisionTreeClassifier
model=DecisionTreeClassifier()
model.fit(xtrain,ytrain)
ypred=model.predict(xtest)
accuracy_score(ytest,ypred)

0.6083333333333333

In [ ]:
#random forest
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier()
model.fit(xtrain,ytrain)
ypred=model.predict(xtest)
accuracy_score(ytest,ypred)

0.6916666666666667

In [ ]:
from xgboost import XGBClassifier
model=XGBClassifier()
model.fit(xtrain,ytrain)
ypred=model.predict(xtest)
accuracy_score(ytest,ypred)

0.6375

In [ ]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(xtrain,ytrain)
ypred=model.predict(xtest)
accuracy_score(ytest,ypred)

0.5625